# Generated by Django 4.2.30 on 2026-08-02 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='总库存')),
                ('locked_quantity', models.PositiveIntegerField(default=0, verbose_name='锁定库存')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='版本号')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_record', to='products.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'SKU 库存',
                'verbose_name_plural': 'SKU 库存',
                'db_table': 'inventory_stock',
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_quantity', models.IntegerField(verbose_name='总库存变化量')),
                ('locked_change', models.IntegerField(verbose_name='锁定库存变化量')),
                ('available_after', models.IntegerField(verbose_name='变更后可售库存')),
                ('reason', models.CharField(max_length=128, verbose_name='变更原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.stock', verbose_name='库存记录')),
            ],
            options={
                'verbose_name': '库存变更日志',
                'verbose_name_plural': '库存变更日志',
                'db_table': 'inventory_stock_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
