# Generated by Django 4.2.30 on 2026-08-02 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='券码')),
                ('name', models.CharField(max_length=128, verbose_name='券名称')),
                ('description', models.TextField(blank=True, verbose_name='券说明')),
                ('type', models.CharField(choices=[('fixed_amount', '满减券'), ('percentage', '折扣券')], max_length=20, verbose_name='类型')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='面值/折扣率')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='最低使用金额')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='最大抵扣金额')),
                ('total_quantity', models.PositiveIntegerField(verbose_name='总发行量')),
                ('remaining_quantity', models.PositiveIntegerField(default=0, verbose_name='剩余数量')),
                ('limit_per_user', models.PositiveIntegerField(default=1, verbose_name='每人限领')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'db_table': 'coupons_coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期')], default='unused', max_length=20, verbose_name='状态')),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='coupons.coupon', verbose_name='优惠券模板')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to='orders.order', verbose_name='关联订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'db_table': 'coupons_user_coupon',
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='抵扣金额')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_coupons', to='orders.order', verbose_name='订单')),
                ('user_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_relations', to='coupons.usercoupon', verbose_name='用户优惠券')),
            ],
            options={
                'verbose_name': '订单优惠券',
                'verbose_name_plural': '订单优惠券',
                'db_table': 'coupons_order_coupon',
                'unique_together': {('order', 'user_coupon')},
            },
        ),
    ]
