# Generated by Django 4.2.30 on 2026-08-02 05:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='品牌名称')),
                ('logo', models.ImageField(blank=True, upload_to='brands/', verbose_name='品牌 Logo')),
                ('description', models.TextField(blank=True, verbose_name='品牌介绍')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'products_brand',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='层级')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'products_category',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('spu_code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SPU 编码')),
                ('name', models.CharField(max_length=128, verbose_name='商品名称')),
                ('description', models.TextField(blank=True, verbose_name='商品简介')),
                ('main_image', models.ImageField(upload_to='products/spu/', verbose_name='主图')),
                ('detail', models.TextField(blank=True, verbose_name='商品详情（支持 HTML）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spus', to='products.brand', verbose_name='品牌')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spus', to='products.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': 'SPU',
                'verbose_name_plural': 'SPU',
                'db_table': 'products_spu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SPUSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='规格名称')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.spu', verbose_name='所属 SPU')),
            ],
            options={
                'verbose_name': 'SPU 规格',
                'verbose_name_plural': 'SPU 规格',
                'db_table': 'products_spu_spec',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('spu', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sku_code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SKU 编码')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='售价')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='成本价')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('sales', models.PositiveIntegerField(default=0, verbose_name='销量')),
                ('status', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认 SKU')),
                ('specs', models.JSONField(blank=True, default=dict, verbose_name='规格组合')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.spu', verbose_name='所属 SPU')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
                'db_table': 'products_sku',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='图片')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.sku', verbose_name='所属 SKU')),
                ('spu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.spu', verbose_name='所属 SPU')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'db_table': 'products_product_image',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpecOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('value', models.CharField(max_length=32, verbose_name='选项值')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.spuspec', verbose_name='所属规格')),
            ],
            options={
                'verbose_name': '规格选项',
                'verbose_name_plural': '规格选项',
                'db_table': 'products_spec_option',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('spec', 'value')},
            },
        ),
    ]
